### PR TITLE
Remove backwards compatibility mode.

### LINKED ISSUE #14: Re-think use of "Backwards Compatibility" and replace with something more appropriate
@trishankatdatadog noted in https://github.com/secure-systems-lab/signing-spec/pull/13#issuecomment-756383812 that the term "backwards compatible" could be misleading. "Legacy" and "Deprecated" were suggested as alternatives, and @MarkLodato said this replacement could occur in a standalone PR.

### PR DESCRIPTION
**Pull request by MarkLodato**
This mode allowed for the old signature protocol to be represented in
the new data structure. However, there was no known use case for this.
True backwards compatibility requires supporting both protocol *and*
data structure. Thus, backwards compatibility can be handled at the
application (TUF or in-toto).

Fixes #14.

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
This PR is good, but I don't think we should say #14 is fixed unless we add text on how `backwards compatibility can be handled at the application (TUF or in-toto).`

**Comment by MarkLodato** [comment]
Good point. Please see the new commit. Does that address? If not, could you give more guidance? Thanks!

**Comment by trishankatdatadog** [comment]
Much better, thanks! For TUF, you might wish to refer to [TAP 14](https://github.com/theupdateframework/taps/blob/master/tap14.md), written by @mnm678.

**Review by adityasaky — APPROVED** [review]
LGTM!

**Comment by adityasaky** [comment]
I'm happy to update re the change in TUF being in line with what's laid out in TAP-14, @MarkLodato, and we can probably merge this one.

**Review by SantiagoTorres — APPROVED** [review]

**Comment by MarkLodato** [comment]
Thanks!

**Pull request merged**
