### PR TITLE
Replace magic payloadType with explicit sigType.

### LINKED ISSUE #5: Backwards compatible `payloadType` should be an exact match
With 2c38369, the backward compatible `payloadType` was changed to a suffix match. This has two disadvantages over an exact match:

* It provides a false sense of security since the prefix is unauthenticated. An attacker could change a legitimate signature's `payloadType` from `foo/backwards-compatible-json` to `bar/backwards-compatible-json` without invalidating the signature. If the consumer relies on `payloadType`, this could be a security vulnerability. Using an exact match avoids this.
* (minor) It is ever-so-slightly harder to describe and implement.

I recommend making it a fixed string.

By the way, the reason I originally wrote it as a non-URI string was so that URI always meant PAE and all magic values were non-URIs. I don't have a problem with having a magic URI, but just FYI in case you want to switch back to the original value. (I don't feel strongly.)

### PR DESCRIPTION
**Pull request by MarkLodato**
This closes #5 and is an alternative to pull request #8. Here, we switch from a magic `payloadType` to an explicit `sigType`, as discussed in #8. My preference is to use this PR and reject #8.

Note: This PR depends on #11 and #12. Sadly, GitHub does not support dependent PRs, so those PRs are show in this one's diff. :-(  The only commit in this PR is the last one, f0518cf.

### CODE REVIEW

**Comment by adityasaky** [comment]
#11 and #12 have now been merged.

**Comment by MarkLodato** [comment]
Thanks! This PR is now ready for review.

**Comment by trishankatdatadog** [comment]
Random question:

Honestly, if we're gonna do this far, why not just index signatures by keyids? Is there a good reason for redundant, possibly conflicting signatures from the same keyid?

**Comment by MarkLodato** [comment]
Hmm, good point. Let me rephrase to make sure I understand: Instead of having a sigType at all, the verifier knows that key X is always old-style and key Y is always new-style. A corollary is that it would be impossible to ever use the same key with both old- and new-style signatures. If you have an existing key, you need to provision a new key to get new-style signatures.

No objections from me, but I don't know how difficult it will be for users to provision new keys. If you all are OK with it, I can make that change. Let me know.

**Comment by MarkLodato** [comment]
On second thought, I'm not sure that's a good idea. If we remove sigType, then the layout is going to need a new field stating whether each key will be used for old-style or new-style signatures. Plus, since it's a new field, it will have to be set explicitly on every new layout going forward. Given this, as well as the burden of having to re-provision new keys, I'm inclined to keep it as is.

What do you think?

**Comment by trishankatdatadog** [comment]
No, that's not what I meant, but let me get back to you.

**Comment by trishankatdatadog** [comment]
> No, that's not what I meant, but let me get back to you.

Sorry this took a while.

Leaving aside my [earlier tangent](https://github.com/secure-systems-lab/signing-spec/pull/13#issuecomment-755571018), I don't think it's accurate to call canonical JSON signatures "backwards-compatible mode."

There's two types of backwards-compatibility:
1. Break backwards-compatibility in metadata (like what this PR proposes), but don't change how signatures are actually decoded and verified.
2. Do not break backwards-compatibility in metadata for the sake of old clients that do not have the luxury to upgrade.

This PR does not maintain (2), which is harder to achieve, and so I think calling it "backwards-compatible" signatures is a misnomer.

**Comment by MarkLodato** [comment]
Right, "backward compatible" is perhaps too far a stretch. Maybe "legacy"? My intention is to make it clear that it is not recommended for new use cases.

**Comment by trishankatdatadog** [comment]
> Right, "backward compatible" is perhaps too far a stretch. Maybe "legacy"? My intention is to make it clear that it is not recommended for new use cases.

I figured this was the intent, too. Maybe it's best to call it "deprecated" or "canonical" (the most appropriate name TBH).

**Comment by adityasaky** [comment]
I like the idea of calling it "legacy" or "deprecated". A question as a relative newcomer, but is there any danger of "canonical" being misinterpreted once the spec is accepted and is the new "canonical" way of doing things? I may be overthinking this, though.

**Comment by adityasaky** [comment]
@MarkLodato I'm planning to accept and merge #13 and close #8 with the change in semantics re "Backwards Compatibility". Does that sound good to you?

cc @SantiagoTorres

**Comment by MarkLodato** [comment]
@adityasaky Yes, sounds good. Thanks! FYI, I just pushed a new commit fixing a mistake.

I agree with Aditya that "canoncial" sounds like "recommended" which is not what we want. I suggest "legacy" since that implies that it is not recommended for new use cases.

To be clear, this PR does not add any new use of the term "backwards compatible." My latest commit (fba2968) removes an incorrect reference to the term. The sigType is "raw-json-no-payload-type". So, I suggest any replacing of the term be done in a separate PR.

**Comment by SantiagoTorres** [comment]
> @MarkLodato I'm planning to accept and merge #13 and close #8 with the change in semantics re "Backwards Compatibility". Does that sound good to you?
> cc @SantiagoTorres

This sounds like a plan to me!

**Review by adityasaky — APPROVED** [review]
I'm merging #13 and I'll shortly be closing #8. Thank you, @MarkLodato and @trishankatdatadog!

**Comment by adityasaky** [comment]
> To be clear, this PR does not add any new use of the term "backwards compatible." My latest commit (fba2968) removes an incorrect reference to the term. The sigType is "raw-json-no-payload-type". So, I suggest any replacing of the term be done in a separate PR.

I've opened #14 to track this. :)

**Pull request merged**
